### ISSUE TITLE
Please add Laravel 8 support

### ISSUE THREAD

**Issue by mischasigtermans** [hotrush/laravel-backup-telegram-notifications#1]
🤙🏽

**Comment by hotrush** [comment]
Added

**Comment by hotrush** [comment]
@mischasigtermans some more changes needed, doesn't work properly

**Comment by hotrush** [comment]
So, now it's correct. Version you used is compatible with laravel 8, but not with spatie/laravel-backup ^7.
Tagged new v2 version and made it compatible with spatie/laravel-backup ^7.
Both versions compatible with laravel 8, see readme for more info

**Comment by mischasigtermans** [comment]
Working on my end, thanks!
