### ISSUE TITLE
Question: return value must be of type string

### ISSUE THREAD

**Issue by schonhose** [hotrush/laravel-backup-telegram-notifications#5]
When trying to send a message after a backup is created by laravel-backup from Spatie, I get the following error in my logs:

```
production.ERROR: Hotrush\SpatieBackup\Notifications\Notifiable::routeNotificationForTelegram(): Return value must be of type string, null returned {"exception":"[object] (TypeError(code: 0): Hotrush\\SpatieBackup\\Notifications\\Notifiable::routeNotificationForTelegram(): Return value must be of type string, null returned at vendor/hotrush/laravel-backup-telegram-notifications/src/Notifications/Notifiable.php:11)
```
Any idea how to solve this?

**Comment by hotrush** [comment]
@schonhose I think you have not set channel id properly, its config path is `backup.notifications.telegram.channel_id`. Check readme for some example

**Comment by schonhose** [comment]
@hotrush thanks. I am assuming you are referring to the following code from the readme?
```
'telegram' => [
    'channel_id' => env('BACKUP_TELEGRAM_CHANNEL'),
],
```
My .env file does not have this parameter, where or how can I obtain the correct value?

**Comment by hotrush** [comment]
@schonhose you can check this gist https://gist.github.com/mraaroncruz/e76d19f7d61d59419002db54030ebe35

**Comment by schonhose** [comment]
Thanks, that was indeed the problem. For further reference, this [site](https://neliosoftware.com/content/help/how-do-i-get-the-channel-id-in-telegram/) provides a more up to date description regarding the channel id in telegram.

Thanks again for your swift response!
